// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iioyauxrpfluuurxdfwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpb3lhdXhycGZsdXV1cnhkZndkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMTc0NDEsImV4cCI6MjA3NTc5MzQ0MX0.SbOTjzDumOq-cUx9wxdFlXoCbAZc_DT2W-lPvYLA2RM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});